### ISSUE TITLE
Intrisic imaging : StimulatorDL090503 error

### ISSUE THREAD

**Issue by maika88** [HelioScan/HelioScan#293]
Hello, 

I'm currently having an issue with Helioscan regarding the stimulator. 

Helioscan already run with a configuration without stimulator.

Afterwords, I tried to configure StimulatorDL090503.
I selected Stimulator DL090503 in main  - Helioscan.lvproj-configuration_manager-ImagingModeMG091111IntrinsicImaging-stimulator.

However, I couldn't start Helioscan.
The programs progress bar remains at please wait and does not proceed at which then the program freezes and crashes. 
As written above I have tried to configure the stimulator but it also refuses to save.

What am I supposed to do?
PC conditions are below.

Labview 2010 SP1
Helioscan 3.10.0
Windows 7, Intel Core i7 CPU, 32bit

Regards,

**Comment by mtedaldi** [comment]
Problem solved
